
The following have been reloaded with a version change:
  1) cuda/9.0.176 => cuda/10.2.89

Traceback (most recent call last):
  File "./TensorFlow/nikhil-mnist.py", line 4, in <module>
    import tensorflow as tf
  File "/share/apps/tensorflow/1.5.0/python2.7/lib/python2.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/share/apps/tensorflow/1.5.0/python2.7/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/share/apps/tensorflow/1.5.0/python2.7/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/share/apps/tensorflow/1.5.0/python2.7/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/share/apps/tensorflow/1.5.0/python2.7/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/share/apps/tensorflow/1.5.0/python2.7/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
ERROR: Malloc trainingData Host failed: CUDA driver version is insufficient for CUDA runtime version
